# Generated by Django 4.2.30 on 2026-05-25 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('release_date', models.DateField()),
                ('developer', models.CharField(max_length=255)),
                ('category', models.CharField(default='General', max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='games_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
